branches:
  only:
  - source

language: node_js
sudo: false

node_js:
  - '6'

before_install:
  - git config --global user.name "Pengfei Ni"
  - git config --global user.email feiskyer@gmail.com

install:
  - npm install hexo-cli -g
  - npm install

script:
  - echo "  repo: https://${GitHubKEY}@github.com/feiskyer/feiskyer.github.io.git" >> _config.yml
  - hexo deploy --generate

notifications:
  slack:
    secure: HrHSWyLLyTlcLjF46C2IChEKsqBhFGPOdv/S1j2iAZRalQPNxj0ctkKCeL8IJTjetQzHhqE8oiNr3glelvAACGB/cHBxJ7uqYF4C37m1pPpK4fYWvQY2UbttfrOvZtTSEI8wmG6iOwcsEsb/qB+YGhg3XPA4CJMuGrKFwhRq951+QckC81xvuQhbl5PYvu788tKt6CyAcxcDPKHv230f5K0kKc/KPRGZw+bJ/3BnYAve5CMbEuBGV7/7BPBBWLJeSv3e3laLytAX9/K8JiQwtsUxm05fgOTkUwy846CPI/qkTOCwl3uf3VPVYIxQaBxMXFF9/pU6RTDlKwuFPf+aDQn3e6xueQsPTqZMJbS++HYqz2o7w3uRLXQ3YmtN5sxcaUws6jzGTsT2CdiS2R4e9tLoGk0CNnmvJIcTgos/WyXQeCnR2kJeoSjOA1UUXhj8Ny2jQN5IB8wp4y9LZH8MTW2g2UPmqLOAv8bYu4BMlX3+w2HBa5oVEUPbRILGVaiOE6DpFwFecHMHm8WRTtoxfTP1jfhE+pAjekVWVJ7YSoiTF3wNdNGIX5UIfiaVMCuq6ZX3QyZ9OvoWeZlYAaZoKfq38QWbOMP57FPS09dTD+gdMpx86YXGjayLxIVcJ5oE6ZgvSMnElRFj3v5wy8xrZIHvwPMkOlJTKIHWXk267Bk=
