baseURL = "https://feisky.xyz/"
languageCode = "zh-Hans"
title = "Feisky"
theme = "even"
description = ""
Paginate = 10
publishDir = "docs"
disqusShortname = "feisky"
hasCJKLanguage = true
googleAnalytics = "UA-69699206-1"
metaDataFormat = "yaml"
enableEmoji = true
buildDrafts = true
enableGitInfo = true
enableRobotsTXT = true

[Params]
  # RSSLink = "/index.xml"
  # author = "Feisky" # add your company name
  # github = "feiskyer" # add your github profile name
  # twitter = "feisky" # add your twitter profile
  version = "3.x"           # Used to give a friendly message when you have an incompatible update
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda

  since = "2014"
  logoTitle = "Feisky"
  keywords = ["Kubernetes", "Cloud","SDN"]
  description = ""
  archivePaginate = 10
  dateFormatToUse = "2006-01-02"
  moreMeta = true

  toc = true
  autoCollapseToc = true
  fancybox = true
  mathjax = true
  mathjaxEnableSingleDollar = true
  postMetaInFooter = true
  linkToMarkDown = false
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'
  baidu_push = true
  baidu_analytics = "d2f4aad4d3f8dc2de9170fa1df3fcbcf"
  baidu_verification = ""   # Baidu Verification
  google_verification = ""  # Google_Verification

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []
  customJS = []

[Params.publicCDN]        # load these files from public cdn
  enable = false
  jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
  slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
  fancyboxJs = '<script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js" integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=" crossorigin="anonymous"></script>'
  fancyboxCss = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css" integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=" crossorigin="anonymous">'
  gitmentJS = '<script src="https://cdn.jsdelivr.net/npm/gitment@0.0.3/dist/gitment.browser.min.js" crossorigin="anonymous"></script>'
  gitmentCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/gitment@0.0.3/style/default.min.css" crossorigin="anonymous">'

[Params.gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments
  clientId = ""           # Your client ID
  clientSecret = ""       # Your client secret

[Params.flowchartDiagrams]# see https://blog.olowolo.com/example-site/post/js-flowchart-diagrams/
  enable = true
  options = ""

[Params.sequenceDiagrams] # see https://blog.olowolo.com/example-site/post/js-sequence-diagrams/
  enable = true
  options = ""            # default: "{theme: 'simple'}"

[Params.busuanzi]         # count web traffic by busuanzi
  enable = false
  siteUV = true
  sitePV = true
  pagePV = true

[Params.reward]
  enable = false
  wechat = "/path/to/your/wechat-qr-code.png"           # 微信二维码
  alipay = "/path/to/your/alipay-qr-code.png"           # 支付宝二维码

[Params.social]
  c-twitter = "https://twitter.com/feisky"
  g-github = "https://github.com/feiskyer"
  h-weibo = "https://weibo.com/371069890"
  i-zhihu = "https://www.zhihu.com/people/feisky"

[author]
  name = "Feisky"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
    name = "分布式系统"
    weight = -100
    url = "/distributed/"

[[menu.main]]
    name = "读书笔记"
    weight = -100
    url = "/docs/"

[[menu.main]]
    name = "机器学习"
    weight = -100
    url = "/machine-learning/"

[[menu.main]]
    name = "容器"
    weight = -100
    url = "/container/"

[[menu.main]]
    name = "知乎"
    weight = -100
    url = "https://zhuanlan.zhihu.com/kubernetes"

[[menu.main]]
    name = "SDN"
    weight = -100
    url = "https://sdn.feisky.xyz"

[[menu.main]]
    name = "Kubernetes"
    weight = -100
    url = "https://kubernetes.feisky.xyz"
