baseURL = "https://feisky.xyz/"
languageCode = "zh-cn"
title = "Feisky"
theme = "hyde"
publishDir = "docs"
disqusShortname = "feisky"
hasCJKLanguage = true
googleAnalytics = "UA-69699206-1"
metaDataFormat = "yaml"
enableEmoji = true
buildDrafts = true
enableRobotsTXT = true

[params]
  # themeColor = "theme-base-0d"
  description = "Notes about anything"
  paginate = 10

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
    name = "Distributed"
    weight = -6
    url = "/distributed/"

[[menu.main]]
    name = "Readings"
    weight = -5
    url = "/docs/"

[[menu.main]]
    name = "机器学习"
    weight = -4
    url = "/machine-learning/"

[[menu.main]]
    name = "Containers"
    weight = -100
    url = "/container/"

[[menu.main]]
    name = "SDN"
    weight = -1
    url = "https://sdn.feisky.xyz"

[[menu.main]]
    name = "Kubernetes"
    weight = -100
    url = "https://kubernetes.feisky.xyz"

[[menu.main]]
    name = "About"
    weight = 100
    url = "/about/"
